name: TestSSh2

on:
  pull_request:
    branches: [ "master" ]

jobs:

  sshConnect:
    runs-on: ubuntu-latest
    steps:
      - name: Connect
        run: |
          echo '${{vars.SSH_KEY}}'
          echo '${{vars.SSH_KEY}}' >> ~/.ssh/id_rsa
          ssh -p 2229 -v ${{vars.SSH_USER}}@${{vars.SSH_HOST}}
          echo connected successfully
